[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "zoo-wes-runner"
dynamic = ["version"]
description = "ZOO-Project-DRU runner using toil WES to process an Application Package encoded in CWL."
authors = [
    { name = "Alex Manning", email = "alexander.manning@stfc.ac.uk" },
    { name = "Gérald Fenoy", email = "gerald.fenoy@geolabs.fr" }
]
readme = "README.md"
packages = [{include = "zoo_wes_runner"}]
license = {text = "Apache License (2.0)"}
requires-python = ">=3.8"

dependencies = [
    "httpx>=0.24.1",
    "cwl-utils",
    "zoo-runner-common"
]

[project.urls]
Documentation = "https://github.com/ZOO-Project/zoo-wes-runner#readme"
Issues = "https://github.com/ZOO-Project/zoo-wes-runner/issues"
Source = "https://github.com/ZOO-Project/zoo-wes-runner"

[tool.black]
line-length = 100
target-version = ['py311']

[tool.isort]
profile = "black"

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 100

[tool.hatch.metadata]
allow-direct-references=true

[tool.coverage.run]
source_pkgs = ["zoo_calrissian_runner", "tests"]
branch = true
parallel = true
omit = [
  "zoo_calrissian_runner/__about__.py",
]

[tool.coverage.paths]
zoo_calrissian_runner = ["zoo_calrissian_runner"]
tests = ["tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.hatch.envs.default.env-vars]
PIP_EXTRA_INDEX_URL = "https://test.pypi.org/simple/"

[tool.hatch.envs.default]
skip-install = false
dependencies = [
    "httpx>=0.24.1",
    "cwl-utils",
    "zoo-runner-common"
]


[tool.hatch.envs.test]
skip-install = false
dependencies = [
    "nose2",
    "coverage",
    "httpx>=0.24.1",
    "cwl-utils",
    "zoo-runner-common"
]

[tool.hatch.envs.test.env-vars]
PIP_EXTRA_INDEX_URL = "https://test.pypi.org/simple/"
RETRY_ATTEMPTS="0"

[tool.hatch.envs.test.scripts]
test = "hatch run nose2"
testv = "hatch run nose2 --verbose"
cov = ["coverage run --source=zoo_wes_runner -m nose2", "coverage report"]

[tool.hatch.version]
path = "zoo_wes_runner/__about__.py"

[[tool.hatch.envs.test.matrix]]
python = ["3.8", "3.9", "3.10", "3.11", "3.12"]

[tool.hatch.envs.docs]
skip-install = false

dependencies = [
  "pdocs",
  "mkdocs-material",
  "mkdocs-jupyter"
]

[tool.hatch.envs.docs.scripts]
serve = "mkdocs serve"
deploy = "mkdocs gh-deploy --force"

